### ISSUE TITLE
global environment parameter

### ISSUE THREAD

**Issue by luogni** [stepchowfun/toast#257]
Is it possible to add a global environment parameter defined for all tasks? For example:
```
image: ubuntu
default: release
environment:
  RELEASE: 1.4.40

tasks:
  download:
    command: wget link_to_$RELEASE

  build:
    command: tar xzf path_to_$RELEASE.tar.gz
```

**Comment by stepchowfun** [comment]
Note for anyone who finds this issue: we'll discuss this in https://github.com/stepchowfun/toast/pull/258.

**Comment by stepchowfun** [comment]
Hi @luogni, I think this is already possible because environment variables persist across tasks (because Docker bakes them into the image metadata). Your example could be written as:

```yaml
image: ubuntu
tasks:
  set_up_environment:
    environment:
      RELEASE: 1.4.40

  download:
    dependencies:
      - set_up_environment
    command: wget link_to_$RELEASE

  build:
    dependencies:
      - download
    command: tar xzf path_to_$RELEASE.tar.gz
```

Let me know if that addresses your use case.
