### ISSUE TITLE
Automatically disable cache when needed

### ISSUE THREAD

**Issue by DannyBen** [stepchowfun/toast#431]
**Description**

When exposing ports without setting `cache: false`, there is an error.

```
[ERROR] Unable to parse file /vagrant/temp/toast.yml. Reason: Task server exposes ports but does not disable caching. To fix this, set cache: false for this task.
```

Instead of showing an error, why not disable the cache?

**Alternatives considered**

docker-compose... 😄 

**Additional context**

I was testing with this toastfile:

```yaml
image: dannyben/alpine-ruby

tasks:
  setup:
    command: gem install httpme

  server:
    # cache: false 
    dependencies: [setup]
    ports: ["3000:3000"]
    input_paths: [docroot]
    command: httpme 
```
