### ISSUE TITLE
Remote execution via DOCKER_HOST incurs 50x ping latency.

### ISSUE THREAD

**Issue by lynaghk** [stepchowfun/toast#440]
First, let me say that Toast is really well done! I haven't done anything with Docker/containers before, but the Toast README is succinct and clear, and I'm impressed with how you've kept the scope focused. Nice job, and thanks for sharing it with us!

I'm investigating using Toast from a Mac to run tasks on a remote backend via the `DOCKER_HOST` env var. However, doing so introduces substantial latency beyond what I'd expect from network overhead. It could be that this is entirely in the Docker engine and out of scope for Toast, but I figured it'd be worth raising here in case anyone has a similar use case and possible suggestion for how to improve the situation.

I'm testing by running this minimal toast.yml:

```yaml
image: ubuntu:20.04@sha256:c01a10535d9ea3e4065dee4abdb288821b2918929f1e1584287a03e731b9176c
command_prefix: set -euo pipefail
tasks:
  hello:
    cache: false
    command: echo "hello world" > my_output
    output_paths:
      - my_output
```

and all of the numbers below refer to `Docker version 20.10.13, build a224086` on an EC2 ARM machine with Toast 0.45.5.
The only difference is whether I invoke toast from a terminal on the EC2 machine or from my Mac. Ping to the EC2 machine is 20--30 ms.

SSH has a 2s login overhead, so it's out of the question. I'm using TCP instead, here's the command I'm using from my Mac:

    LOG_LEVEL=debug DOCKER_HOST=tcp://containertron:2375 toast hello 2>&1 | ts "[%.S]"

(The `ts` adds a microsecond timestamp to each printed log line.)

Here's a comparison between execution from the Mac and from a terminal on the server. Note that the remote execution via `DOCKER_HOST` takes about 1s longer than a local execution on the EC2 server:

<img width="1150" alt="Screen Shot 2022-07-25 at 10 42 59 PM" src="https://user-images.githubusercontent.com/147919/180932235-9af87424-713b-4b44-8106-4af0989774f4.png">

Again, I have no experience with docker, but can field a few guesses:

+ TCP connection overhead
+ a bunch of 25 ms round-trips between the Docker CLI and the engine
+ protocol overhead (if Docker chats something different over TCP than UNIX socket?)
+ DNS resolution overhead across Toast's multiple invocations of `docker`

Do you have any suggestions for things to investigate to improve the latency here? Thanks!
